config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'tags/:tag', to: 'posts#index', as: :tag

  resources :posts do
    resources :comments

    member do
    	put "like" => "posts#upvote"
    	put "unlike" => "posts#downvote"
    end
  end

  resources :tags, only: [:index, :show]

  root 'posts#index'




end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post


  
end

app/models/post.rb
class Post < ActiveRecord::Base
	
	has_many :comments
	
	#第一个参数对应的是Post中的属性字段名，第二个参数是用来上传图片的类名（即刚刚用rails g uploader Picture生成的类）
	mount_uploader :picture, PictureUploader
	
	validate :picture_size
	acts_as_taggable # Alias for acts_as_taggable_on :tags
  	acts_as_taggable_on :skills, :interests
  	acts_as_votable

	private

	def picture_size
		if picture.size > 5.megabytes
			errors.add(picture: "不能上传超过5MB的图片")
		end
	end


end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_voter




  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all.order("created_at DESC")
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :tag_cloud

  def tag_cloud
    @tags = Post.tag_counts_on(:tags).order('count desc').limit(20)
  end

  def upvote
    @post.upvote_from current_user
    redirect_to posts_path
  end

  def downvote
    @post.downvote_from current_user
    redirect_to posts_path
  end






  # GET /posts
  # GET /posts.json
  def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tag]).order(created_at: :desc)
    else
      @posts = Post.all.order(created_at: :desc)
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
   
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:content, :picture, :tag_list)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  include ActsAsTaggableOn::TagsHelper




end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.text_field :post_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
      <div class="col-md-3">        
          <br> --- <br>
          <% @comments.each do |comment| %>
              <%= comment.body %>
              <br>
              <%= link_to '更多评论' %>
          <% end %>

          <div class="body_todo">
            感谢 + 1 | <%= f.input :comment %> | ...(举报弹出框)
          </div>
        
      </div> 

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>绝版照片</title>
  <meta id="viewport" name="viewport" content="width=device-width, user-scalable=no, initial-scale, minimum-scale=1, maximum-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/posts">绝版照片</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/posts">首页 <span class="sr-only">(current)</span></a></li>
        <li class="btn-info right"><%= link_to '上传绝版照片', new_post_path(@post) %></li>
      </ul>

      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">搜索</button>
      </form>
    </div><!-- /.navbar-collapse -->

  </div><!-- /.container-fluid -->
</nav>


<div class="pinterest">
  <%= yield %>
</div>

<footer>
<div class="container center">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
    反馈邮箱 : 2243980491 | 2016 绝版照片
    </div>
  </div>
</div>
</footer>
</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post, html: {multipart: true} do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <br>
    <div class="btn btn-primary">
      <%= f.file_field :picture, accept: "image/jpeg, image/gif, image/png" %>
    </div>
    <br>
    <br>
    <%= f.input :tag_list, :hint => "请填写标签,多标签用逗号(英文输入法下的)隔开." %>
    <%= f.input :content, :hint => "一句话简单描述." %>
    <br>
    <%= f.submit '保存', class: 'btn btn-success' %>

<% end %>

app/views/posts/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">			
			<div class="panel panel-default">
			  <div class="panel-heading">
			    <h3 class="panel-title">修改</h3>
			  </div>
			  <div class="panel-body">
			    <%= render 'form' %>
			  </div>
			</div>

			<%= link_to '返回首页', posts_path %>
		</div>
	</div>
</div>

app/views/posts/index.html.erb
  <div class="container"> 
    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-default">
          <div class="panel-heading">标签云</div>
          <div class="panel-body">
            <div id="tag_cloud">
              <% tag_cloud(@tags, %w(s m l)) do |tag, css_class| %>
                <%= link_to tag.name, tag_path(tag.name), :class => css_class %>
              <% end %>
            </div>
          </div>
        </div>          
      </div>
    </div>
  </div>


  <div class="container">
          <div class="row">
            <% @posts.each do |post| %>  
              <div class="col-md-7">                         
                  <%= image_tag (post.picture_url) if post.picture? %>
                <br>
              </div>
              <div class="col-md-3"> 
                <div class="caption">
                  <%= link_to like_post_path(post), class: "like", method: :put do %>
                    <button class="btn btn-info" type="button" aria-label="Left Align">
                      <span class="glyphicon glyphicon-thumbs-up glyphicon-align-center" aria-hidden="true"></span>
                      <span class="badge"><%= post.get_upvotes.size %></span>
                    </button>
                  <% end %>
                  <%= link_to unlike_post_path(post), class: "like", method: :put do %>
                    <button class="btn btn-info" type="button" aria-label="Left Align">
                      <span class="glyphicon glyphicon-thumbs-up glyphicon-align-center" aria-hidden="true"></span>
                      <span class="badge"><%= post.get_downvotes.size %></span>
                    </button>
                  <% end %>
                </div>
                <br>
                <%= link_to '更多', post_path(post), class: "btn btn-success" %>
                 标签: <%= raw post.tag_list.map { |t| link_to t, tag_path(t) }.join('. ') %>
                 评论数: ?    
                <br>
                <div class="comment">
                    
                </div>
              </div>     
            <% end %>
            <br>
          </div>
  </div>  





        

 

app/views/posts/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">			
			<div class="panel panel-default">
			  <div class="panel-heading">
			    <h3 class="panel-title">创建图片</h3>
			  </div>
			  <div class="panel-body">
			    <%= render 'form' %>
			  </div>
			</div>

			<%= link_to '返回首页', posts_path %>
		</div>
	</div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-md-4">
        <div class="thumbnail">
            <%= image_tag(@post.picture_url) if @post.picture? %>
        </div>
        <div class="caption">
          
          <p><%= @post.content %></p>
        </div> 
        <tr>
          <td><%= link_to '修改', edit_post_path(@post) %></td>          
        </tr> 
    </div> 
    <br>
     人感谢 | 
     人评论 | 
    <%= link_to '标签' %>
    <br> ---


    <br> ---
  </div>
</div>